version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www/api
    ports:
      - '80:80'
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/api
